$ANSIBLE_VAULT;1.1;AES256
38333963326466633132363230373231663735613439363964396534653564623736383666316536
3365353261373539643865333039346363303037336530360a383036346366663862346235326337
36633534633731356237633832326361633036363931613964356363343862386631666566343833
3039353039623231620a353865366138336535343430663939396238616534366237353763356332
64393364363936396535336235653261333436626137326635376238633964393762356334653439
32653463366562316130623131396466383331316165333932306562616162373861613063626662
39353733616264633465363135363531323462636236346432613131333339653962303136666162
33623536316663306565323530373335366432353839396336333434336239386362643962623866
30363564346562393362396266376330633632653034373366643636646165373566663831333732
38363632316234636532333537366434346331646632383838353836633639626262633733656635
62386530623937366535323863326463313831323866336632356131666262356137626631373165
39333037313734313730333732633461653433353461373437336463316433313935616334653334
39356334333362626464346265373266303435623635626263383030373239393335323331303665
34316633373963346163626234303435643265303430666138653839313034623262333338373037
33383436653166633031333263346639353138316463623030656165636631306230376435383061
33653437373037616430643238323665333239346331333862303631386130393431643038383130
66373539623935326664666663313863313963363765613231376634653935373438616164353463
38643735393264383439306231316534623766333732636130343234626339643261653863303836
61343035326565323064356666356533643366626364666430383565376537613438313537393762
31373661643264616161343666333739366536363263363032356331643536343861316639333132
61363739396463393763366139366463646530303133353835393837663635396561326166633265
35386531316331636333333837626637313265356464653533373965333730323030663431623161
626438643464663662336336303737353061
