---
galaxy_info:
  role_name: tailscale
  author: MMS
  description: Install and configure Tailscale with serve mappings
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
