---
# Backup SABnzbd (no stop required - only config files)

- name: "sabnzbd - Create compressed backup of config"
  ansible.builtin.shell:
    cmd: >-
      tar -cf - -C {{ backup_config_dir }}/sabnzbd
      sabnzbd.ini admin
      | zstd -T0 -o {{ backup_dir }}/sabnzbd/sabnzbd-{{ ansible_date_time.date }}.tar.zst
    creates: "{{ backup_dir }}/sabnzbd/sabnzbd-{{ ansible_date_time.date }}.tar.zst"
