---
driver:
  name: docker

platforms:
  - name: traefik-test
    image: fedora:43
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    host_vars:
      traefik-test:
        mms_user: mms
        mms_uid: "3000"
        mms_gid: "3000"
        mms_config_dir: /opt/mms/config
        mms_quadlet_dir: /home/mms/.config/containers/systemd
        mms_systemd_env:
          XDG_RUNTIME_DIR: /run/user/3000
          DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/3000/bus
        mms_network_name: mms
        mms_traefik_domain: test.local
        mms_traefik_routes:
          testapp:
            subdomain: testapp
            container: testapp
            port: 8080
