---
# Proxmox API connection
proxmox_api_host: 192.168.5.20
proxmox_api_port: 8006
proxmox_node: pve1
proxmox_storage: cola-vm-store
proxmox_iso_storage: cola-vm-iso

# VM template
proxmox_template_name: fedora-cloud
proxmox_template_vmid: 9000
