---
# Proxmox API connection
proxmox_api_host: 192.168.1.10
proxmox_api_port: 8006
proxmox_node: pve
proxmox_storage: local-lvm
proxmox_iso_storage: local

# VM template
proxmox_template_name: fedora-cloud
proxmox_template_vmid: 9000
