---
galaxy_info:
  role_name: storage
  author: MMS
  description: NFS mounts and TRaSH-guide-compatible directory structure
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
