---
galaxy_info:
  role_name: traefik
  description: Deploy Traefik reverse proxy using Podman Quadlet
  author: MMS
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
