---
galaxy_info:
  role_name: quadlet_service
  description: Deploy a container service using Podman Quadlet
  author: MMS
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
