---
galaxy_info:
  role_name: migrate
  author: MMS
  description: Migrate services from LXC containers to MMS VM
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
