---
galaxy_info:
  role_name: podman
  description: Configure rootless Podman for the mms user
  author: MMS
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
