---
- name: Provision MMS VM
  import_playbook: provision-vm.yml

- name: Configure base system
  import_playbook: setup-base.yml

- name: Deploy services
  import_playbook: deploy-services.yml

- name: Set up backups
  import_playbook: backup.yml
